__include__: [
  '../dataset/scanly_detection.yml',
  '../runtime.yml',
  './include/dataloader.yml',
  './include/optimizer.yml',
  './include/core_r50vd.yml',
]


output_dir: ./output/core_r18vd_scanly


PResNet:
  depth: 18
  freeze_at: -1
  freeze_norm: False
  pretrained: False


HybridEncoder:
  in_channels: [128, 256, 512]
  hidden_dim: 256
  expansion: 0.5


RTDETRTransformerv2:
  num_layers: 3


eval_spatial_size: [1024, 1024]

epoches: 200

train_dataloader:
  dataset:
    transforms:
      policy:
        epoch: 190
  collate_fn:
    scales: ~
    stop_epoch: 190
  total_batch_size: 4
  num_workers: 2

val_dataloader:
  total_batch_size: 4
  num_workers: 2
